[terminal]
shell = "/usr/bin/fish"
osc52 = "CopyPaste"

[window]
decorations = "None"
opacity = 0.7

[window.padding]
x = 4
y = 4

[font]
size = 11.5

[font.normal]
family = "Iosevka Nerd Font"
style = "SemiBold"

[font.bold]
family = "Iosevka Nerd Font"
style = "Heavy"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[colors]
transparent_background_colors = true

[colors.primary]
background = "#191724"
foreground = "#E0DEF4"

[colors.normal]
black = "#26233A"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#31748F"
magenta = "#C4A7E7"
cyan = "#EBBCBA"
white = "#E0DEF4"

[colors.bright]
black = "#6E6A86"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#31748F"
magenta = "#C4A7E7"
cyan = "#EBBCBA"
white = "#E0DEF4"

[cursor]
blink_interval = 500
blink_timeout = 30

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"
