[terminal]
shell = "/usr/bin/fish"
osc52 = "CopyPaste"

[window]
decorations = "None"
opacity = 0.7

[window.padding]
x = 4
y = 4

[font]
size = 11.5

[font.normal]
family = "Iosevka Nerd Font"
style = "SemiBold"

[font.bold]
family = "Iosevka Nerd Font"
style = "Heavy"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[colors]
transparent_background_colors = true

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black = "#000000"
red = "#FF5555"
green = "#55FF55"
yellow = "#FFFF55"
blue = "#5555FF"
magenta = "#FF55FF"
cyan = "#55FFFF"
white = "#BBBBBB"

[colors.bright]
black = "#555555"
red = "#FF5555"
green = "#55FF55"
yellow = "#FFFF55"
blue = "#5555FF"
magenta = "#FF55FF"
cyan = "#55FFFF"
white = "#FFFFFF"

[cursor]
blink_interval = 500
blink_timeout = 30

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"
