sort_by = "position" # "none" | "position" | "application"
max_windows = 3

name = "title" # "class" | "title"
name_case = "none" # "none" | "lowercase" | "uppercase"
name_max_length = 20
name_padding = 1

separator_string = ""
empty_desktop_string = "desktop"

active_window_left_click   = "minimize"
active_window_middle_click = "close"
active_window_right_click  = "none"
active_window_scroll_up    = "none"
active_window_scroll_down  = "none"

inactive_window_left_click   = "raise"
inactive_window_middle_click = "close"
inactive_window_right_click  = "none"
inactive_window_scroll_up    = "none"
inactive_window_scroll_down  = "none"

active_window_fg_color = "none"
active_window_bg_color = "#29ffffff"
active_window_ul_color = "#ffffff"

inactive_window_fg_color = "#43ffffff"
inactive_window_bg_color = "none"
inactive_window_ul_color = "#43ffffff"

separator_fg_color = "none"
separator_bg_color = "none"
separator_ul_color = "none"

empty_desktop_fg_color = "none"
empty_desktop_bg_color = "none"
empty_desktop_ul_color = "#ffffff"

overflow_fg_color = "#43ffffff"
overflow_bg_color = "none"
overflow_ul_color = "#43ffffff"

ignored_classes = [
    # "foo",
    # "bar"
]

[window_nicknames]
firefox = "  Firefox"
alacritty = "  Alacritty"
spotify = "  Spotify"
discord = "  Discord"
steam = "  Steam"
chrome = "  Chrome"
